/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/common/TrackBar copy.vue')['default']
    CustomDivider: typeof import('./src/components/common/CustomDivider.vue')['default']
    Divider: typeof import('./src/components/common/Divider.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconButton: typeof import('./src/components/common/IconButton.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LeftSidebar: typeof import('./src/components/layout/LeftSidebar.vue')['default']
    LeftSideButtons: typeof import('./src/components/layout/LeftSideButtons.vue')['default']
    MusicPlayer: typeof import('./src/components/layout/MusicPlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TrackBar: typeof import('./src/components/common/TrackBar.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
